### ISSUE TITLE
Tip

### ISSUE THREAD

**Issue by NiiV3AU** [lilkajt/Steam-Account-generator#1]
# The code block
https://github.com/lilkajt/Steam-Account-Generator/blob/32a3de10cdd4e79015569c8b4cfca8614133d519/Script/SAG.py#L51-L53
# Tip 
You dont need to specify a function you just need to add this to the beginning:
```python
from time import sleep as sleep
```
If you done it this way you can call the function any time like you did in your project ↴
```python
sleep(n)
```
<details>
<summary><b>Reminder</b> ↴</summary>
This is not a solution to a problem but just keep this in mind as you dont need to define a new time functions each time you need the sleep function in new projects of yours.
</details>

**Comment by lilkajt** [comment]
yeah, I know. Thanks.
I was trying different things because I couldn't **compile the script into .exe using pyinstaller**. Didn't find a solution still, so I might use a different library.

Thats why you might find code that make no sense.

**Comment by NiiV3AU** [comment]
Did you tried auto-py-to-exe? Its using pyinstaller but its easier to change settings for the compiling. You can look there and test if different settings work for this project. Though I dont know the error you are getting and which specific option in pyinstaller is responsible for it.

**Comment by lilkajt** [comment]
There wasn't specific error during compilation. When I compiled the program, it crashed immediately after starting. I think it's cuz of the pyinstaller. I didn't try different methods. I'll try yours. Thanks
